au-ts/sddf

drivers/network/imx/ethernet.c, drivers/network/meson/ethernet.c, examples/echo_server/echo_server.system, network/components/arp.c, network/components/copy.c, network/components/lwip.c, network/components/mux_rx.c, network/components/mux_tx.c, network/components/udp_echo_socket.c, network/components/utilization_socket.c, network/ipstacks/lwip/src/core/ipv4/ip4.c, network/ipstacks/lwip/src/core/tcp_in.c, network/ipstacks/lwip/src/core/udp.c, util/include/util.h
This updates the ethernet components to the latest protocol, as well as the meson and imx ethernet drivers. The sDDF example systems build but are untested.
=> Update sDDF ethernet protocol

.github/workflows/ci.yaml, ci/acquire_sdk.sh
A temporary solution until we can pin a release of the official Microkit SDK
=> ci: use latest dev Microkit SDK

drivers/serial/arm/uart.mk, drivers/serial/imx/uart.mk, drivers/serial/meson/uart.mk, serial/components/serial_components.mk, util/util.mk
Add build snippets for the serial path
=> Build snippets

serial/components/virt_rx.c
The serial multiplexer only dequeues one character at a time in the handle_rx() path. This is incorrect, as it is possible that the serial driver signalled the mux several times before it got a chance to run, meaning that there could be several characters to consume.
=> serial: consume all enqueued characters in mux_rx

examples/echo_server/Makefile, examples/echo_server/board/imx8mm_evk/echo_server.system, examples/echo_server/board/maaxboard/echo_server.system, examples/echo_server/board/odroidc4/echo_server.system, include/sddf/util/util.h, network/components/virt_rx.c, util/cache.c
These fixes should be all that are needed to fix the packet corruption we were seeing.
=> Fix virt_rx cache invalidation

README.md
This is something people will want to frequently reference so we should link to it in the README.
=> README: explicitly link design documentation

.gitignore
This gets generated when running the style check
=> Add *.orig to gitignore

examples/echo_server/include/lwip/arch/cc.h, examples/i2c/pn532.h, include/sddf/blk/fsmalloc.h, include/sddf/blk/msdos_mbr.h, include/sddf/blk/util.h, include/sddf/i2c/client.h, include/sddf/network/arp.h, include/sddf/serial/util.h, include/sddf/util/cache.h, include/sddf/util/ialloc.h
The other changes are to pass the CI style check.
=> Add pragma once to header files

examples/echo_server/include/ethernet_config/ethernet_config.h
Hopefully the last kind of this PR I have to make but I doubt it.
=> examples/echo_server: style ethernet config

examples/echo_server/echo.h, examples/echo_server/echo.mk, examples/echo_server/include/ethernet_config/ethernet_config.h, examples/echo_server/include/lwip/lwipopts.h, examples/echo_server/lwip.c, examples/echo_server/tcp_echo_socket.c, examples/echo_server/udp_echo_socket.c, include/sddf/util/util.h, network/components/virt_rx.c, network/ipstacks/lwip/src/Filelists.mk
This adds a TCP echo server operating on port 1237, similar to the existing UDP one on port 1235.
=> TCP echo server

include/sddf/blk/queue.h
Always add to the tail and take from the head of a queue. Also, use pointers to reduce the need for repeated arithmetic rather than rely on the compiler optimiser.
=> Swap head and tail in block queue

include/sddf/util/util.h
Broke in 22d208b2903c74a8088e9df5bedb71686309515d.
=> Fix assert from being undefined

.github/workflows/pr.yaml
I keep having to fix trailing whitespace so let's add this change.
=> ci: add check for trailing whitespace

drivers/network/imx/ethernet.c
This PR removes a fragment of code from an older version of sDDF that disables receive interrupts if the HW ring is empty, and re-enables them if it is non-empty.
I believe last year there was more interrupt switching on/off in the ethernet driver, but we don't use it any more. From experimentation it doesn't seem like this code is invoked, and if it were, it doesn't make much sense as we should not be receiving rx IRQs for incoming packets if the HW ring is empty, since there are no buffers available for the device to receive into.
I removed this code, and adjusted the surrounding code to account for the fact that we no longer change which IRQs are enabled during run-time (except for during initialisation).
To be sure that this did not effect performance, I re-benchmarked the IMX before …
=> Remove interrupt disabling code on the IMX ethernet driver.

blk/components/virt.c
This patch gives slightly more responsibility to the system designer by having a new 'blk_partition_mapping' in the block config header.
This allows us to give certain partitions to certain clients. There is still more policy configuration to be desired, however this will allow us to at least easily test block drivers/disks now.
An example of such a mapping is (from #157)
```c
/* Mapping from client index to disk partition that the client will have access to. */
static const int blk_partition_mapping[BLK_NUM_CLIENTS] = { 2 };
```
=> blk: allow more flexibility with client partitions

sound/components/sound_components.mk
Adds Makefile snippet for the sound virtualiser.
=> sound: add makefile snippet

include/sddf/serial/queue.h
Add many characters to a queue using memcpy()
=> Add batch add interface to serial subsystem

blk/components/virt.c, include/sddf/blk/queue.h
- Renamed function names e.g. from blk_req_queue_full -> blk_queue_full_req etc.
- Prefixed request codes with BLK to prevent clashes with other (soon to be merged) device classes
=> Rename blk queues to match other device classes

blk/components/virt.c
Probably should have a return code for fsmalloc_free as well.
=> blk: add extra asserts to virtualiser

drivers/blk/virtio/block.c, drivers/blk/virtio/block.h
See commit messages for details.
=> Minor virtIO block driver fixes

blk/components/virt.c, drivers/blk/virtio/block.c, examples/blk/board/qemu_virt_aarch64/blk.system
See commit messages for details.
=> Various fixes in block system

examples/echo_server/Makefile, examples/echo_server/board/imx8mp_evk/echo_server.system, examples/echo_server/include/ethernet_config/ethernet_config.h, include/sddf/network/constants.h
This also works for the Compulab iotg-imx8plus board.
=> Add imx8mp_evk board

README.md
Forgot to do this in https://github.com/au-ts/sddf/commit/8443f267a1f175d312c75e5a8b2b93808fbe1ab3.
=> README: update to sdfgen 0.16.1

.github/workflows/examples.yaml, README.md, docs/developing.md, drivers/blk/mmc/imx/config.json, drivers/blk/virtio/config.json, drivers/i2c/meson/config.json, drivers/network/imx/config.json, drivers/network/meson/config.json, drivers/network/virtio/config.json, drivers/serial/arm/config.json, drivers/serial/imx/config.json, drivers/serial/meson/config.json, drivers/serial/snps/config.json, drivers/timer/arm/config.json, drivers/timer/imx/config.json, drivers/timer/jh7110/config.json, drivers/timer/meson/config.json, flake.lock, flake.nix
Only relevant change is that I removed the 'name' field from config.json files since it's redundant.
=> Update to sdfgen 0.19.1

.github/workflows/examples.yaml, README.md, build.zig.zon, examples/blk/build.zig.zon, examples/gpu/build.zig.zon, examples/i2c/build.zig.zon, examples/serial/build.zig.zon, examples/serial/meta.py, examples/timer/build.zig.zon, flake.lock, flake.nix
Breaking change introduced regarding package manifests.
Hopefully the last time I have to do this for a while as 0.14.0 is supposed to release on 3rd of March and we'll pin to that rather than what we're doing now which is tracking master.
=> Update for Zig 0.14.0-dev.3445+6c3cbb0c8

examples/echo_server/meta.py
Needs https://github.com/au-ts/sddf/pull/358 first.
=> examples/echo_server: use auto-generated MAC addr

drivers/network/dwmac-5.10a/ethernet.c, drivers/network/imx/ethernet.c, drivers/network/meson/ethernet.c
While working on the pancake Ethernet driver, @JunmingZhao42 noticed that the `net_buff_desc` metadata array stored in the `hw_ring` data structures was not actually used. She noticed that only the address of the buffer was used by the driver, but not the length as it is always overwritten.
On further inspection, I realised that the address was also not needed, as a duplicate copy is stored within each hardware descriptor ring entry. Consequently, I have removed the entire net buffer descriptor array from the Ethernet `hw_ring` data structure, and instead read the address of each buffer from the corresponding hardware descriptor entry.
This is a simple change for the `imx` and `meson` drivers, however I felt that it was necessary to change the names of the descriptor entries in the …
=> Remove buffer descriptor array from eth driver metadata region

.github/workflows/examples.yaml, README.md, flake.nix
=> Update to Microkit 2.0.0

.github/workflows/examples.yaml
Less changes needed for when we update versions of things.
=> ci: simplify examples.yml

examples/echo_server/echo.mk, examples/serial/serial.mk, examples/timer/timer.mk
Now we can run builds with more than one CPU.
=> make: fix dependencies for echo_server + board tracking

.github/workflows/examples.yaml, README.md, examples/blk/meta.py, examples/echo_server/meta.py, examples/i2c/meta.py, examples/serial/meta.py, examples/timer/meta.py, flake.lock, flake.nix, include/sddf/serial/config.h, serial/components/virt_tx.c
Main difference is fixes for getting GPT partitioning working (needed more data region between virtualiser and driver for initialisation) and cleaning up 'begin string' in serial sub-system.
=> Upgrade to sdfgen 0.24.0

.github/workflows/examples.yaml
=> ci: use nproc when building examples

examples/blk/README.md
some development setup things Ive stumbled on when setting up new PC.
=> examples:blk:Update README.md

LICENSES/SHL-0.51.txt, ci/matrix.py, drivers/serial/ns16550a/include/uart.h, drivers/serial/ns16550a/uart.c, dts/cheshire.dts, examples/serial/build.zig, examples/serial/meta.py, examples/serial/serial.mk
This PR adds support for the Cheshire SoC to the ns16550a driver + driver example.
=> Added support for Cheshire to ns16550a

drivers/serial/ns16550a/include/uart.h, drivers/serial/ns16550a/uart.c
As discussed, the 'SHADOW' part is a bit mis-leading.
=> drivers/serial/ns16550a: rename DW APB support define

.github/workflows/examples.yaml
=> ci: actually run macOS Nix on macOS

examples/echo_server/README.md
One point I am not sure about though is how QEMU decides which client to send traffic to...
=> examples/echo_server: improve docs

.github/workflows/examples.yaml, ci/matrix.py, examples/echo_server/README.md, examples/echo_server/echo.mk, examples/echo_server/meta.py, flake.nix
See commit messages for details.
=> Add imx8mp_iotgate to echo server and fix matrix.py

include/sddf/i2c/i2c_driver.h, include/sddf/i2c/queue.h
* Some minor style fixes
* One actual bug fix
=> i2c: minor fixes
