au-ts/sddf

network/ipstacks/lwip/src/core/inet_chksum.c
network/ipstacks/lwip/src/core/ipv4/etharp.c
network/ipstacks/lwip/src/core/ipv4/ip4.c
network/ipstacks/lwip/src/core/pbuf.c
network/ipstacks/lwip/src/core/tcp_in.c
network/ipstacks/lwip/src/core/udp.c
network/ipstacks/lwip/src/netif/ethernet.c

Most of these are just duplicates of existing LWIP debug prints so if they are needed it would be better to fix the originals.
This also removes a dependency on util.h which is desirable because util.h is a grab-bag of echo server stuff we should be trying to reorganise.

Remove debug prints from LWIP

---

.github/workflows/ci.yaml
ci/examples.sh
examples/echo_server/Makefile
examples/timer/Makefile

Lots of people developing now, and things are easily breaking.
We obviously need run-time tests as well but there's still lots of pieces moving around in the sDDF so this will catch the build failures at least.

Add initial CI

---

drivers/i2c/meson/include/sw_shared_ringbuffer.h
include/sddf/network/shared_ringbuffer.h
network/libethsharedringbuffer/shared_ringbuffer.c
serial/libserialsharedringbuffer/include/shared_ringbuffer.h

Overflow in ringbuffer picked up by verifast, probably never going to be an issue in practice.

fix: overflow in ringbuffer

---

examples/timer/Makefile
examples/timer/client.c
include/sddf/timer/client.h
timer/client/Makefile
timer/client/client.c

Having the timer driver's channel as a preprecessor macro means that for systems that contain multiple programs using the timer, either every program must have the same channel number for the timer driver, or the client library needs to be built independently for different programs. This may be too constricting until we develop an ergonomic way to specify and build Microkit systems.
This commit modifies the API of the timer client library to accept the timer's channel as a parameter.
This also has the side effect that a program could use multiple timer devices simultaneously. Not sure how much value there is there.

Add explicit channel argument to timer client library

---

drivers/serial/meson/include/uart.h
drivers/serial/meson/uart.c

This is a quick-and-dirty approach until we have a systematic way of dealing with getting the device registers within a driver (most likely integrated with the device tree of a platform etc).
Needed by @alwin-joshy for his GDB work.

serial: enable using Meson UART with other platforms

---

examples/echo_server/Makefile
include/sddf/network/constants.h
include/sddf/network/util.h
include/sddf/util/util.h
network/components/arp.c
network/components/mux_rx.c

This commit changes the mux_rx and arp ethernet components to no longer depend on lwIP. lwIP was only used lightly in these components to parse ethernet headers, so the relevant constants (which are defined by standards) were duplicated into new files in include/sddf/network/constants.h. Additionally, a macro BYTE_ORDER was added to include/sddf/util/util.h and an implementation of htons was duplicated into include/sddf/network/util.h. New names were given to duplicated identifiers so that they will not clash with lwIP if included by a component which also uses lwIP.

Remove lwIP dependency from ethernet RX multiplexer and ARP components

---

benchmark/benchmark.c
benchmark/idle.c
drivers/clock/imx/timer.c
drivers/clock/meson/timer.c
drivers/i2c/meson/i2c.c
drivers/network/imx/ethernet.c
drivers/network/meson/ethernet.c
examples/echo_server/include/lwip/arch/cc.h
examples/echo_server/lwip.c
examples/echo_server/udp_echo_socket.c
examples/echo_server/utilization_socket.c
examples/i2c/client.c
examples/i2c/pn532.c
i2c/components/virtualiser.c
include/sddf/util/printf.h
include/sddf/util/util.h
network/components/arp.c
network/components/copy.c
network/components/mux_tx.c
util/printf.c
util/putchar_debug.c
util/putchar_serial.c

We are encountering in LionsOS that our custom sDDF printf is clashing with printf from libc. This is a temporary measure to ensure systems using libc can be built with sDDF.
We have two options to deal with this:
* sDDF either declares the minimal libc functionality it needs (memcpy, some str functions, printf etc) and it is up to the user of sDDF to bring these functions along.
* Use our libc tailored for Microkit/LionsOS in this repository.
It is not clear what we will do yet.

Fix printf to not clash with other printfs

---

examples/i2c/client.c
include/sddf/i2c/client.h

Abstracts over the possible interactions to the virtualiser, this will decrease the duplicated code across clients but more importantly, will mean that slight changes to the API with the virtualiser do not lead to breaking changes to the clientss since they aren't doing PPC directly.

i2c: add helpers for claiming and releasing a bus

---

benchmark/benchmark.c
benchmark/idle.c
drivers/clock/imx/timer.c
drivers/clock/meson/timer.c
drivers/i2c/meson/i2c.c
drivers/network/imx/ethernet.c
drivers/network/meson/ethernet.c
examples/echo_server/lwip.c
examples/i2c/client.c
examples/i2c/pn532.c
i2c/components/virt.c
include/sddf/util/printf.h
network/components/arp.c
network/components/copy.c
network/components/virt_tx.c

This makes sddf_printf (and others) be recognised as printf by the compiler, and raise warnings if the arguments don't match the format string.

Support emitting warnings for incorrectly using sddf printf functions.

---

include/sddf/util/util.h

When included via SDDF queue headers into micropython, we get a double defined assert() macro.  Only define assert if it is not already defined.

Avoid doubly defined assert

---

serial/components/virt_rx.c

Null terminating `got_char` in virt rx.

Fixed bug with non null terminated string with atoi

---

include/sddf/util/ialloc.h

This simple utility library allows you to allocate and free indices ranging from 0 to some initialised size. It is currently useful to clients of the blk system who need to generate a matching req/resp ID, and also to those who are implementing virtio drivers (frontend).

Add index allocator helper util

---

blk/components/virt.c
blk/util/bitarray.c
blk/util/fsmalloc.c
blk/util/util.c
include/sddf/blk/bitarray.h
include/sddf/blk/fsmalloc.h
include/sddf/blk/msdos_mbr.h
include/sddf/blk/queue.h
include/sddf/blk/util.h

This PR provides a virtualiser implementation for sDDF blk. It parses an msdos/mbr partition table in order to allocate one partition to one client. It uses memcpy to transfer client and driver data. This is done for now for simplicity with an existing driver VM implementation, but I expect in the near future we pass a physical pointer to do DMA.
Also includes minor changes to sDDF queue in regards to the queue size hash defines

blk virtualiser

---

examples/echo_server/Makefile
examples/i2c/Makefile
examples/serial/Makefile
util/newlibc.c

This was a hack done to make it easier to develop but turns out the toolchain we use packages newlibc which can be easily used instead.

Remove checked in libc

---

include/sddf/util/ialloc.h

`ialloc_init` in `include/sddf/util/ialloc.h` is currently not static and should be (since it is in a header file)

Make `ialloc_init` static

---

drivers/clock/imx/timer.c
drivers/clock/meson/timer.c

This was my fault since I thought you could do this kind of initialisation when defining the array but turns out that only works for zero-init.

Fix initialisation in timer drivers

---

blk/components/virt.c
include/sddf/util/ialloc.h

Currently both virtIO block and virtIO sound use this allocator. It doesn't need to be 64-bit as we will never need more than UINT32_MAX indices (currently we use at most 4096). Both sDDF ID fields are already 32-bit. I am updating the virtIO devices to reflect this change in https://github.com/au-ts/libvmm/pull/37

Change ialloc from 64-bit to 32-bit

---

.github/workflows/examples.yaml

We need llvm-ar as well which isn't in the clang or lld package. We can just install the llvm package which will install everything we need.

ci: install all LLVM tools

---

benchmark/benchmark.c
examples/echo_server/Makefile
examples/echo_server/board/imx8mm_evk/echo_server.system
examples/echo_server/board/maaxboard/echo_server.system
examples/echo_server/board/odroidc4/echo_server.system
examples/echo_server/lwip.c
network/components/virt_rx.c
network/components/virt_tx.c

This change adds a reference count for each buffer in the virt rx component. This allows us to properly handle broadcast packets that need to be sent to multiple clients, and ensuring that we are still adhering to the consumer/producer pattern that is expected. On broadcasts, we set the refcount to the number of clients in the system, and for unicast just 1. We decrement the refcount when we receive a buffer back from the client, and enqueue back into the driver queues when the refcount reaches zero.

net: add refcounts for buffs in virtrx to account for broadcast packets

---

include/sddf/network/queue.h

While it's not necessary, knowing the size of a queue is very useful for debugging.
We used to have this but it got removed accidentally.

net: add size function back and style

---

benchmark/benchmark.c
examples/echo_server/board/imx8mm_evk/echo_server.system
examples/echo_server/board/maaxboard/echo_server.system
examples/echo_server/board/odroidc4/echo_server.system
examples/echo_server/include/ethernet_config/ethernet_config.h

f4e08e5408776ec6ea900c162506bea6a1f7ec35 needed to also make certain changes to the ethernet configuration header to account for the removal of the ARP component.

examples/echo server: fix regressions

---

.gitignore

Trival change to add Emacs backup files to the ones for git to ignore.

Add emacs backups to gitignore

---

examples/echo_server/echo.mk

lwip.elf needs the non-debug version of libsddf_util.a

Fix release-mode builds

---

include/sddf/blk/queue.h
include/sddf/i2c/queue.h
include/sddf/network/queue.h

Closes https://github.com/au-ts/sddf/issues/111.
Brought up by @isubasinghe.

Remove redundant `% size` from queue APIs

---

drivers/network/meson/eth_driver.mk
examples/echo_server/echo.mk
examples/i2c/i2c.mk
examples/timer/timer.mk
libco/libco.mk
network/components/network_components.mk
util/util.mk

Various cleanups and fixes to enable the Kitty LionsOS example to use the sDDF, plus some others:
-- Always build the CHECK_FLAGS_BOARD_MD5 file, so changes from DEBUG->Release or similar will force rebuilds.
-- Hide object files in a named subdirectory of the build directory wherever possible, to allow conflicting-named files
-- various consistency cleanups
-- Reduce reliance on VPATH/vpath

Makefile fixes

---

examples/i2c/board/odroidc4/i2c.system
include/sddf/i2c/queue.h

The I2C data region is currently bound to 12,800 bytes. The request/response regions are currently limited to 4008 bytes.

Use appropriate size for i2c memory regions

---

blk/components/virt.c

Removed in f1efff160a8eee65489df1baa8fc8a0824662332, but we need these still.
Ideally the virtualiser would not need access to the data, but that's a seperate issue that we intend to fix.

blk: add back data region globals

---

.github/workflows/examples.yaml
.gitignore
build.zig
build.zig.zon
ci/examples.sh
examples/echo_server/board/imx8mm_evk/echo_server.system
examples/echo_server/board/maaxboard/echo_server.system
examples/echo_server/board/odroidc4/echo_server.system
examples/echo_server/board/qemu_arm_virt/echo_server.system
examples/echo_server/echo.mk
examples/i2c/README.md
examples/i2c/build.zig
examples/i2c/build.zig.zon
examples/serial/README.md
examples/serial/board/imx8mm_evk/serial.system
examples/serial/board/maaxboard/serial.system
examples/serial/board/odroidc4/serial.system
examples/serial/board/qemu_arm_virt/serial.system
examples/serial/build.zig
examples/serial/build.zig.zon
examples/serial/include/serial_config/serial_config.h
examples/serial/serial.mk
examples/serial/serial_server.c
examples/timer/build.zig
examples/timer/build.zig.zon
serial/components/serial_components.mk
serial/components/virt_tx.c

A preliminary zig build system for sDDF. This exposes the sddf headers to be included by dependent systems, and also components and drivers as artifacts.

Support Zig build systems

---

ci/examples.sh

Accidentally commented these out in b4631a76bdacabd32583ff93c41be8d1efcc0983.

ci: uncomment accidentally commented examples

---

blk/components/virt.c
include/sddf/blk/queue.h

This PR changes the addr field in the blk queues to use offsets instead of virtual addresses. It also refactors the virtualiser component to expect a blk_config header file supplied by each system that describes the size and layout of each memory region needed in the blk subsystem.

Change blk queue to use offsets, and refactor to use blk_config.h

---

build.zig

Upstreaming building block subsystems with zig with blk_config.h instead of passing around a BLK_NUM_CLIENTS hash define.
This PR is rebased on #144 and should be merged after.

Zig blk fixes

---

drivers/network/meson/ethernet.c

This PR fixes the meson driver bug causing the driver to lose DMA buffers during TCP benchmarking.

Fix driver bug

---

drivers/network/meson/ethernet.c
drivers/network/meson/ethernet.h

This PR enables flow control and operate on second hardware features in the meson ethernet driver that improve UDP performance for the odroidc4. 
UDP throughput is improved for the odroidc4, TCP throughput is actually reduced, but with more consistency and lower CPU utilisation. It was decided that we would optimise for UDP performance for now.

Use more hardware features in meson ethernet driver

---

build.zig
examples/i2c/build.zig
examples/serial/build.zig
examples/timer/build.zig

My fault, this should not have been merged. When we were first adding all the build.zigs in the examples we were having runtime crashes and I thought it was due to UBSAN so added a bunch of `-fno-sanitize=undefined`.
I've run the serial and timer examples and they all run fine with UBSAN enabled so I think it's fine to remove all these extra flags. After all, we should be fixing the UB if we have any, not disabling the UB checks.

build.zig: remove -fno-sanitize options

---

include/sddf/util/util.h

Partially solves https://github.com/au-ts/sddf/issues/161 and removes warning when colliding with LibVMM's `util.h`

`util.h`: add ifndef for `ROUND_UP`, `MIN` and `MAX`

---

blk/components/virt.c
include/sddf/blk/queue.h

This patch renames the storage info struct to use 'capacity' instead of 'size' to make it clearer what the field means.
Also renames 'queue_size' to 'capacity' since size could refer to how many entries are in a queue or the max number of entries.

blk: use capacity where it makes sense

---

drivers/network/imx/ethernet.c
drivers/network/meson/ethernet.c
drivers/network/virtio/ethernet.c
drivers/serial/arm/uart.c
drivers/serial/imx/uart.c
drivers/serial/meson/uart.c
examples/echo_server/board/imx8mm_evk/echo_server.system
examples/echo_server/board/maaxboard/echo_server.system
examples/echo_server/board/odroidc4/echo_server.system
examples/echo_server/board/qemu_arm_virt/echo_server.system
examples/echo_server/include/ethernet_config/ethernet_config.h
examples/echo_server/include/serial_config/serial_config.h
examples/echo_server/lwip.c
examples/serial/include/serial_config/serial_config.h
network/components/arp.c
network/components/copy.c
network/components/virt_rx.c
network/components/virt_tx.c
serial/components/virt_rx.c
serial/components/virt_tx.c

This PR updates the networking components so that all queue variable declarations have the correct type, as opposed to many using `uintptr_t`. Declaring all microkit patching variables as `uintptr_t` seems to be a relic of the past.
As such, the network initialisation functions in 'ethernet_config.h' and 'serial_config.h' required a signature update.
This PR also removes a handful of unused variables from prior implementations.

Update network and serial style

---

examples/echo_server/echo.mk

Currently the utilisation and UDP echo ports are forwarded but not TCP echo. It makes sense to expose TCP echo too.

echo_server: add TCP echo server forwarding to qemu

---

examples/i2c/pn532.c
include/sddf/i2c/queue.h

It is ambiguous and so we use 'length' to mean how many entries are in a given queue and 'capacity' to mean the maximum length/size of a queue.

i2c: do not use 'size'

---

include/sddf/serial/queue.h
serial/components/virt_tx.c

This patch adds 6 possible colours for clients, reusing the colours when we have more than 6 clients. If this becomes limiting then we can revisit this strategy but for now this is simple and will work for all of our use-cases.
Closes https://github.com/au-ts/sddf/issues/141.
The output of the serial example now looks like:

serial: avoid certain colours in TX virt

---

examples/serial/include/serial_config/serial_config.h

This stops the serial tx virtualiser from transmitting the null character at the end of the init string, which causes garbled output in some cases.

Stop serial virt_tx transmitting NULL character

---

examples/echo_server/lwip.c
examples/serial/serial_server.c
util/putchar_serial.c

This PR changes `_sddf_putchar` to automatically enqueue a '\r' character when it is called with a '\n' character. This emulates the behaviour of `microkit_dbg_putc` so that the output of a client is the same, whether `sddf_printf` is linked with `putchar_serial` or `putchar_debug`.

Add carriage return printf

---

serial/components/virt_tx.c

Big error that caused the serial tx virt to crash revealed itself while integrating the subsystem with LionsOS. This PR updates the ring buffer queue to work correctly.

Fix big error with ring buffer implementation in serial virt tx

---

drivers/network/virtio/ethernet.c

This is a small optimisation in the virtIO net driver that means the virtIO net device will not be needlessly invoked if we have not been able to enqueue any TX data. This scenario could happen under high-loads where the virtIO net queues are full but we have more client TX data to process.

net/virtio: only set QueueNotify if we have transferred data

---

blk/components/virt.c

Requires adding the blk_data_driver_paddr to the system file.
Set BLK_VIRT_PASS_OFFSETS to revert to the previous behaviour.
Needed for #157

Pass physical addresses to the block driver PD instead of offsets

---

blk/components/blk_components.mk

Add block component Makefile snippet. Needed for https://github.com/au-ts/libvmm/pull/79.

blk: add makefile snippet

---

network/components/copy.c

This PR updates the network copy component to not depend on `string.h` and instead use `sddf/util/string.h`. This allows the network components to be compiled without built in string functions. 
Surprisingly, utilising the byte by byte `sddf_memcpy` does not seem to negatively impact performance. I took two samples on the IMX8mm and odroidc4:
Requested_Throughput,Receive_Throughput,Send_Throughput,Packet_Size,Minimum_RTT,Average_RTT,Maximum_RTT,Stdev_RTT,Median_RTT,Idle_Cycles,Total_Cycles
IMX8MM -`sddf_memcpy`: 1000000000,957035645,999995450,1472,1329,1516,1944,97.95,1471,6230124072,23058230899 (0.7298)
IMX8MM -built in `memcpy`: 1000000000,957447712,999994417,1472,1340,1519,1959,94.60,1475,0,6262811899,23007070662 (0.7277)
odroidc4 -`sddf_memcpy`: …

Remove string.h dependence from the networking copy component

---

examples/timer/README.md

Realised this was missing when adding the JH7110 timer driver to the example.

examples/timer: add README

---

network/components/virt_rx.c
util/cache.c

These functions were copy-and-pasted from the seL4 kernel where
they are intended to be *inclusive* ranges, this is not the case
for us though. We want to clean the cache *up to* the value of
`end`.
Bug noticed by @midnightveil because the block virtualiser does cache clean on a single data region and hence the last virtual address would have been memory that the virtualiser does not have.
I suspect this issue hasn't occurred before because we have contiguous memory and so the last virtual address would have just overlapped with another region of memory. I need to double check this though.
Closes https://github.com/au-ts/sddf/issues/182.

Fix cache bug

---

blk/components/virt.c
sound/components/virt.c

I haven't gotten the chance to add the cache operations to mainline libmicrokit yet so we're going to do raw system calls for now.
Made an issue about it here https://github.com/au-ts/sddf/issues/195 so we don't forget.

More fixes for Microkit 1.4.0

---

serial/components/virt_tx.c

This PR changes the serial tx virtualiser to signal a client after their data has been transmitted to the driver's data region. The primary purpose for this is to enable clients to wait on a notification from the virtualiser if they wish to transmit data but their data region is currently full. 
The signalling of the client is dependent on whether the client sets their notify consumer flag, thus receiving a signal from the tx virtualiser is opt in depending on the client's behaviour.

Serial tx virt signal client when space available

---

ci/examples.sh
drivers/blk/mmc/imx/README.md
drivers/blk/mmc/imx/include/usdhc.h
drivers/blk/mmc/imx/mmc_driver.mk
drivers/blk/mmc/imx/usdhc.c
examples/blk/mmc/Makefile
examples/blk/mmc/README.md
examples/blk/mmc/board/maaxboard/mmc.system
examples/blk/mmc/client.c
examples/blk/mmc/include/configs/blk_config.h
examples/blk/mmc/mmc.mk

This is a driver for the MaaXBoard SD host controller, based on the following documents:
- i.MX 8M Dual/8M QuadLite/8M Quad Applications Processors Reference Manual
Document Number: IMX8MDQLQRM, Rev 3.1, 06/2021.
https://www.nxp.com/webapp/Download?colCode=IMX8MDQLQRM
- SD Specifications Part 1 Physical Layer Simplified Specification.
Version 9.10, Dec. 2023.
https://www.sdcard.org/downloads/pls/
- SD Specifications Part A2 SD Host Controller Simplified Specification.
Version 4.20, July 2018.
https://www.sdcard.org/downloads/pls/
- IRQ & DMA based driver
- Supports 3.3V operation of Version 2 SDHC cards (4GiB–32GiB) at $f_{OD}$ (400kHz).
- Voltage Negotiation (anything but 3.3V)
- Version 1 SD cards (the initialisation flow)
- Version 2 SDSC / SDXC cards (only because I haven't …

IMX8MQ (MaaXBoard) uSDHC Driver

---

ci/examples.sh
examples/blk/mmc/README.md
examples/blk/mmc/board/imx8mm_evk/mmc.system

I tested that the basic MMC example works on the iMX8 Mini EVK, and it does, so might as well include the system file.

examples/blk: Add a imx8mm_evk system to the example

---

build.zig
drivers/i2c/meson/README.md
drivers/i2c/meson/driver.h
drivers/i2c/meson/i2c.c
drivers/i2c/meson/i2c_driver.mk
examples/i2c/README.md
examples/i2c/board/odroidc4/i2c.system
examples/i2c/build.zig
examples/i2c/client_ds3231.c
examples/i2c/client_pn532.c
examples/i2c/i2c.mk
i2c/components/virt.c
i2c/devices/ds3231/README.md
i2c/devices/ds3231/ds3231.c
i2c/devices/ds3231/ds3231.mk
i2c/devices/pn532/README.md
i2c/devices/pn532/pn532.c
i2c/devices/pn532/pn532.mk
include/sddf/i2c/devices/ds3231/ds3231.h
include/sddf/i2c/devices/pn532/pn532.h
include/sddf/i2c/queue.h

- added ds3231 device driver
- updated and refactored pn532 driver
- reorganised them to be outside of example directory and into driver directory
- fixed bugs and refactored i2c driver
- updated readme for i2c driver to be correct for the current implementation
- removed previous pn532 client example
- created new ds3231+pn532 example where they both the clients use the bus simultaneously 
- updated the board for 2 clients
- updated queue.h for an extra field
- updated the virtualiser so it can facilitate 2 clients instead of 1
- added makefiles and readmes to each directory I created.
- added an mp4 video showing the card reader working

i2c: fixes, improvements and expanding the example

---

blk/components/virt.c
drivers/blk/virtio/block.c
include/sddf/blk/queue.h

- BLK_RESP_OK: When request succeeds
- BLK_RESP_ERR_UNSPEC: Miscelleanous errors
- BLK_RESP_ERR_INVALID_PARAM: Request gives invalid parameters, e.g. passing a physical address thats out of bounds
- BLK_RESP_ERR_SEEK: read/write request block number is invalid
- BLK_RESP_ERR_NO_DEVICE: can't handle request because the device is unplugged

Add new error codes to sddf block

---

drivers/serial/meson/uart_driver.mk
serial/components/serial_components.mk

We shouldn't be reliant on the parent Makefile to add libsddf_util_debug.a to LIBS, so for the components that need it make this an explicit input to the final link, and tell Make it's needed.

Add explicit dependencies on libsddf_util_debug.a

---

drivers/blk/mmc/imx/README.md
drivers/blk/mmc/imx/usdhc.c
examples/mmc/client.c
examples/mmc/mmc.mk
include/sddf/blk/queue.h

*  The in-tree code relied on a lot of assertions and would crash in
the presence of any sort of errors, e.g. card removal.
*  This new implementation handles command errors uniformly in a new
`handle_interrupt_status()` function, and returns varying error types
up the call stack and to the block queues.
Further/more detailed changes are:
*  The INT_STATUS register is now only read once on an interrupt, to
prevent subtle race conditions.
*  Soft failures from:
-  Card not expecting an APP_CMD following CMD55
-  Incompatible voltage ranges, or unsupported card types
-  Incorrect card check commands from CMD8
*  sDDF Block queues are only ever initialised once
*  Indefinite busy-wait loops on Command Inhibit fields are replaced
with an error return, as they never happen in usual operation. …

blk: Make the i.MX8 mmc driver more robust to errors

---

drivers/blk/mmc/imx/README.md
drivers/blk/mmc/imx/include/usdhc.h
drivers/blk/mmc/imx/usdhc.c

Tested on on a 2GiB SDSC Card, matches with mmc-utils on Linux.
```
CSD Version: 0
READ_BL_LEN: a
C_SIZE: eaf
C_SIZE_MULT: 7
uSDHC DRIVER|ERROR: Card size (blocks): 481280
Hello from client
[   0] = 0x3
[   1] = 0x4
[   2] = 0x5
[   3] = 0x6
[ 508] = 0xff
[ 509] = 0x0
[ 510] = 0x1
[ 511] = 0x2
[ 512] = 0x3
[ 513] = 0x4
[ 514] = 0x5
[ 515] = 0x6
[ 516] = 0x7
[4092] = 0xff
[4093] = 0x0
[4094] = 0x1
[4095] = 0x2
[4096] = 0x3
[4097] = 0x4
[NW-3] = 0x0
[NW-2] = 0x1
[NWB-] = 0x2
[NWB=] = 0x0
[NWB+] = 0x0
[NW++] = 0x0
[NR-2] = 0x0
[NR-1] = 0x0
[NRB=] = 0x3
[NR+1] = 0x4
[NR+2] = 0x5
[NR+3] = 0x6
Client read/write data is correct!
```
In theory, should also work on SDXC (32GiB -> 2TiB) and SDUC (> 2TiB), though we don't have cards to test.
Waiting on #206 to merge first.
Part of #187.

Add support for SDSC (≤2GiB) SD cards

---

examples/blk/build.zig

It was annoying because it was creating it in the example directory instead of the build directory which meant that it kept showing up in my git status.

examples/blk: change how disk is created in build.zig

---

benchmark/benchmark.c
examples/echo_server/lwip.c

This avoids an 'unexpected channel' message being printed out, everything is fine and nothing needs to be done if we do get a notification from serial TX.

examples/echo_server: catch notify from serial TX

---

examples/echo_server/include/ethernet_config/ethernet_config.h
examples/echo_server/lwip.c
include/sddf/network/util.h
network/components/copy.c
network/components/virt_rx.c
network/components/virt_tx.c

The ethernet_config file currently initializes queues and data structures for the different components. This patch shifts more of the initialization into the components and leaves the bare minimum inside the config file.
The primary motivation behind this for making the sDDF microkit-independent in the future. When this occurs, the assumptions that the sDDF implementation in microkit holds about the relative position of certain buffers and things like this may no longer hold. Changing the implementation to something like this allows us to seperate queue configuration from queue initialization, so that the same initialization code (in the components) can be used by different OS environments, even if parameters about the queues are from different places.

Rework the ethernet_config file

---

.github/workflows/examples.yaml

Looks like they changed it recently and didn't add a redirect.

ci: fix Zig download link

---

drivers/i2c/meson/driver.h
drivers/i2c/meson/i2c.c
i2c/devices/ds3231/ds3231.c
i2c/devices/pn532/pn532.c
include/sddf/i2c/devices/pn532/pn532.h
include/sddf/i2c/queue.h

This pull request fixes a significant inefficiency in the transport layer - previously, data was transferred by having every write arranged as follows
```
|WRITE|DATA|[data]|DATA|[data] ... | DATA|
```
... where each DATA was an identical token indicating that the byte after this is to be treated as a payload to read or write. 
This is more severe in the case of a read, where it would be:
```
|READ|DATA|DATA|DATA|DATA|DATA|DATA|DATA| ..... DATA_END|
```
This has been refactored to remove this redundancy minimally while retaining the same transport layer semantics - i.e. a buffer is shared for the request and the return data. We now transmit a READ or WRITE followed by a buffer size N between 0 and 255. The following N bytes are treated as payloads. This halves the amount of space required …

#176 (I2C) Remove redundant data tokens from transport layer

---

build.zig
drivers/serial/snps/include/uart.h
drivers/serial/snps/uart.c
drivers/serial/snps/uart_driver.mk
examples/serial/board/star64/serial.system
examples/serial/build.zig
examples/serial/serial.mk
util/cache.c

Developed based on the 'DesignWare DW_apb_uart Databook', retrieved from
https://linux-sunxi.org/File:Dw_apb_uart_db.pdf. Version 3.04a,
January 20, 2006.
Also adds support for the Pine64 Star64 to the serial example.

Add Synopsis DesignWare ABP UART driver

---

examples/i2c/client_ds3231.c

if driver returns a response of 0s (because something goes wrong) the client now will not crash

i2c: added index check so if driver screws up client wont break

---

.github/workflows/examples.yaml

The Zig maintainers have asked the community to not use the official download URL for CI and instead use a set of mirrors in a supported GitHub CI action.
All Zig downloads are signed and checked to ensure the mirrors used do not mess with the download.

ci: change how we download Zig

---

LICENSES/LicenseRef-APACHE-2-LLVM-EXCEPTION.txt
drivers/timer/arm/timer.c
include/sddf/util/udivmodti4.h

Fix for https://github.com/au-ts/sddf/issues/178. Adding in support for 128 bit integer division, as we do not have this as part of clang with no std lib. It does however exist in libgcc, but as we are moving away from gcc, this is a temporary fix before writing our own libc.
The multiplication should not overflow for approx ~10 trillion years instead of 5-10 minutes.

Arm timer fix

---

build.zig
ci/examples.sh
drivers/timer/jh7110/timer.c
drivers/timer/jh7110/timer_driver.mk
examples/serial/serial.mk
examples/timer/Makefile
examples/timer/board/star64/timer.system
examples/timer/build.zig
examples/timer/timer.mk

Also adds support for the Pine64 Star64 in the timer example.
This example expects the mainline Microkit to be used which is why it has not been added into the CI script. I will do so once sDDF transitions to the mainline Microkit in the next couple of days.

Add JH7110 timer driver

---

blk/components/virt.c
drivers/blk/mmc/imx/usdhc.c
drivers/blk/virtio/block.c
examples/blk/blk_config.h
examples/blk/board/qemu_virt_aarch64/blk.system
examples/blk/client.c
examples/mmc/board/imx8mm_evk/mmc.system
examples/mmc/board/maaxboard/mmc.system
examples/mmc/client.c
examples/mmc/include/configs/blk_config.h
include/sddf/blk/queue.h
include/sddf/blk/storage_info.h

This PR changes blk virt to use io addresses from client data regions instead of the one shared with the driver. Refer to commit message for more details.
Note: I haven't been able to test this on the hardware examples in examples/mmc

Various fixes to block subsystem

---

blk/components/virt.c

When number of in-flight requests (indicated by ialloc size) is less than or equal to the response queue size, we know for certain it can never be full which renders the check redundant.

blk virt: Replace resp queue full check with assert

---

drivers/network/imx/ethernet.c
drivers/network/meson/ethernet.c
drivers/network/virtio/ethernet.c
drivers/serial/arm/uart.c
drivers/serial/imx/uart.c
drivers/serial/meson/uart.c
drivers/serial/snps/uart.c
examples/echo_server/include/ethernet_config/ethernet_config.h
examples/echo_server/include/serial_config/serial_config.h
examples/echo_server/lwip.c
examples/echo_server/tcp_echo_socket.c
examples/serial/include/serial_config/serial_config.h
include/sddf/network/queue.h
include/sddf/serial/queue.h
network/components/copy.c
network/components/virt_rx.c
network/components/virt_tx.c
serial/components/virt_rx.c
serial/components/virt_tx.c

This PR removes the use of "size" from describing how many entries a queue has. To describe the maximum number of entries that a queue can hold, the word "capacity" is now used. To describe the number of entries a queue currently has, the word "length" is used. Size is still used to describe how large a data region is. 
This PR makes this change for both the serial and networking subsystems. This fixes issue (https://github.com/au-ts/sddf/issues/140) for these subsystems.

Use capacity/length instead of size in network and serial subsystems

---

serial/components/virt_tx.c

This fixes an accidental typo in the list of colours for the serial tx virt that was unfortunately not caught during testing as we didn't use enough clients.

Add missing comma to colours list is serial tx virt

---

include/sddf/network/queue.h

This PR modifies the network queue library to use the entire capacity of the queue, rather than keeping one entry empty. 
Originally, the `head` and `tail` indices where kept modulo the `capacity` of the queue, so we could not use all entries of the queue as if `head == tail` then we could not distinguish between empty and full.
The indices are no longer kept modulo the capacity, therefore we can now use the entire capacity of the queue as empty and full can be distinguished by `tail - head` (0 meaning empty, capacity meaning full).

Use the entire capacity of the net queue

---

drivers/network/virtio/ethernet.c

We've reached an unrecoverable state, we should just crash.

drivers/net/virtio: assert instead of early return

---

drivers/blk/virtio/block.c
examples/blk/board/qemu_virt_aarch64/blk.system

The i.MX8 uSDHC driver uses `blk_req_queue` and `blk_resp_queue` which makes more sense. So we make the virtIO driver conssitent with it.

drivers/blk/virtio: make setvars consistent with other block drivers

---

drivers/serial/virtio/console.c
drivers/serial/virtio/include/console.h
drivers/serial/virtio/serial_driver.mk
include/sddf/virtio/virtio.h

The motivation for this is to allow multiple serial devices to be used at the same time with QEMU platforms.
Improvements:
* make it use a serial design oriented around DMA instead of byte-by-byte transfer.
* have one 'virtio region' that is used for all virtqs, rx data, tx data.
* revisit descriptor handling, right now we have descriptors of length 1.

drivers/serial: implement virtIO console driver

---

.github/workflows/examples.yaml

macos-12 is deprecated, we don't have aarch64-none-elf version 11 for macOS on Apple Silicon which is what macos-14's environment is. For this reason, we have to update GCC while also updating the macOS version.
Homebrew now packages LLD in a separate package, so we have to install that as well.

ci: update to GCC-12 and use macos-14

---

include/sddf/serial/queue.h

It was pointed out by @alwin-joshy that the descriptions of the serial queue flags and flag functions were incorrect. Since we already use that name `consumer_signalled` in the network queue to indicate whether the consumer of the queue has been signalled, I updated the serial queue library to be in line with this.
This came down to two changes:
- Fixing the function descriptions to accurately describe their usage.
- Swapping which flag corresponds to which side of the queue - prior to this PR, the consumer would set the `producer_signalled` flag to indicate whether it needed to be signalled, and vice versa for the producer. This does not align with the network queue (and the original intention), thus I updated the flag functions so that the consumer now sets the `consumer_signalled` flag …

Fix serial queue flag functions and descriptions

---

drivers/network/dwmac-5.10a/ethernet.c

Hopefully this is what you were expecting in the first place. Only contains the one commit for the fix and has no conflicts.

fix packet length read from descriptor in dwmac

---

examples/blk/build.zig
examples/i2c/build.zig
examples/serial/build.zig
examples/timer/build.zig

This prevents a footgun whereby an environment variable MICROKIT_SDK is set, but a different `-Dsdk=<sdk>` is set as an argument. This is because the Microkit tool uses the boards path from the environment variable preferentially to the path it is installed in.
This aligns the zig build files to the makefiles.

build.zig: Override MICROKIT_SDK environment variable

---

examples/blk/blk.mk
examples/mmc/mmc.mk

To be consistent with all other examples, with the exception of the echo server since it has a dependency on libc.

Move `blk` and `mmc` example to default to Clang

---

drivers/i2c/meson/i2c.c

In `i2c_load_tokens` we're bit-shifting the value of data by potentially more than 8-bits which is undefined behaviour in C if data is uint8_t.
To fix this, we can just make data a uint32_t which makes sense since wdata0 is also uint32_t.

drivers/i2c/meson: fix undefined behaviour

---

flake.nix

This fix makes the unwrapped clang capable to use its built-in headers. Further it tidies up the `mkShell` call a little.
@Ivan-Velickovic Please review, and let me know if the lengthy comment is at least halfway understandable.

fix: clang compiler in devShell

---

examples/echo_server/README.md

* list supported platforms.
* explain why we use GCC for now.
* briefly explain the purpose of the example.
We should document the benchmarking process a bit more, but I will leave that for another time.

examples/echo_server: improve README

---

build.zig
examples/blk/build.zig
examples/gpu/build.zig
examples/i2c/build.zig
examples/serial/build.zig
examples/timer/build.zig

setLinkerScriptPath has been replaced by setLinkerScript. It does the exact same thing, it's just a name change.

Fixes to build.zigs for API change

---

drivers/network/imx/eth_driver.mk
drivers/network/meson/eth_driver.mk
drivers/network/virtio/eth_driver.mk
serial/components/serial_components.mk

When building the network and serial subsystems, I noticed that some object files seem to be in the wrong place/misnamed.
The object files for both the serial virtualisers were placed in the root build directory with the system elfs, and named virt_tx.o and virt_rx.o with no prefix.
The ethernet driver object files were placed in a subdirectory of the build directory corresponding to the device class, but I believe it makes more sense for this subdirectory to reside in the `network` directory, as there is no indication as to what device class the directory corresponds to.
This PR moves the ethernet driver object file directory into the `build/network` directory, and renames the serial virtualiser object files from "virt_[rt]x.o" to "serial_virt_[rt]x.o", and creates the directory …

Fix build directory structure

---

drivers/serial/imx/uart.c

My mistake when integrating the new tooling.

drivers/serial/imx: fix notify in rx_return

---

examples/echo_server/utilization_socket.c

Regression after moving to the new sdfgen tooling.

examples/echo_server: fix regression in utilisation socket setup

---

blk/components/virt.c
drivers/blk/mmc/imx/usdhc.c
drivers/blk/virtio/block.c
include/sddf/blk/queue.h

If we start dealing with block devices in the terabytes, we do risk overflow.

blk: use uint64_t for request block number

---

drivers/network/imx/ethernet.c
drivers/network/meson/ethernet.c

This PR updates the ethernet driver HW rings to comply with sDDF queue conventions. Changes are:
1. Use overflowing unsigneds for head and tail indices (rather than keeping indices modulo ring capacity).
2. Use the entire capacity of the HW rings (rather than keeping 1-2 entries as guard entries which was previously required before changing 1).
3. Keep ring capacity as an element in the HW ring struct. Prior to this PR, it was used as a macro throughout the code, and required as a function parameter to queue functions which already took the queue data structure as a parameter.
4. Correct the memory barriers when reading from and writing to the ring DMA region. This involved the addition of two acquire fences to prevent re-orderings before reading, and the relaxing of a full memory barrier …

Update ethernet driver HW rings

---

drivers/serial/arm/uart.c
drivers/serial/imx/uart.c
drivers/serial/meson/uart.c
drivers/serial/snps/uart.c
drivers/serial/virtio/console.c
examples/serial/client.c
include/sddf/serial/queue.h
serial/components/virt_rx.c
serial/components/virt_tx.c
util/putchar_serial.c

Currently, both the consumer and producer of a serial queue only signal each other if their corresponding flags are set - there are two flags for each queue. This is in contrast to the networking subsystem, where the consumer never signals the producer, and the producer only signals the consumer depending on the value of the flag.
Since the serial subsystem is using a signalling protocol for both directions of communication, it makes the code quite complicated to read and understand for those who are unfamiliar with the protocol. Since the serial subsystem is not performance critical, and the risk of over signalling even with unconditional signalling is very low, I have decided to remove one direction of the signalling protocol so that producers of serial queues signal consumers …

Remove serial signalling protocol from producers to consumers

---

util/putchar_serial.c

While making recent changes to the serial subsystem, I notice a potential deadlock in the `_sddf_putchar` function.
Prior to this PR, the function only signals the `TX_CH` if the queue is full after inserting a character, or if the character inserted was the `FLUSH_CHAR`. However, the function only actually inserts a character into the queue if it is not full, or in the case of a `\n` character, the queue has space for 2 characters.
This means that if the queue only has space for one character, and a `\n` is attempted to be inserted, the function will immediately return without signalling, and there is no guarantee the function signalled on its previous invocation. This is a potential deadlock, as the virtualiser has potentially not yet been signalled for the remaining characters in the …

Fix serial `putchar` newline deadlock

---

ci/examples.sh
drivers/blk/mmc/imx/blk_driver.mk
examples/blk/blk.mk
examples/blk/meta.py

I forgot to add the MaaXBoard into the CI list for building the block example which would have caught this. PR fixes the Makefile and updates the CI script.

Block example fixes

---

flake.lock
flake.nix

Also make zig/sdfgen follow our nixpkgs.

nix: update to nixpkgs-unstable to stop building aarch64-none-elf-gcc

---

dts/qemu_virt_aarch64.dts

I had modified the DTS slightly from what QEMU spits out via dumpdtb when developing the sdfgen tooling. This commit makes the DTS for QEMU exactly what it spits out with dumpdtb.

dts: update qemu_virt_aarch64.dts

---

examples/serial/build.zig
examples/timer/build.zig

We don't use these in the Makefiles.
`secure` is off by default and there is no benefit to doing `highmem=off`.

build.zig: remove redundant QEMU args

---

.reuse/dep5
build.zig
drivers/network/dwmac-5.10a/config.json
drivers/network/dwmac-5.10a/eth_driver.mk
drivers/network/dwmac-5.10a/ethernet.c
drivers/network/dwmac-5.10a/ethernet.h

This PR adds support for dwmac 5.10a ethernet driver, primarily tested on the Pine64 Star64.
These are preliminary performance figures when running the echo_server example. There is still considerable performance improvements to be made.
```
100000000,99984012,100000009,1472,114,298,596,125.48,264,0,0,0
200000000,199901305,200000256,1472,526,726,1022,103.90,727,0,0,0
300000000,299862749,299999187,1472,593,741,913,77.90,737,0,0,0
400000000,399407536,400000656,1472,660,7716,17033,3880.44,7840,0,0,0
500000000,399606637,499999812,1472,20432,23028,25471,1369.32,23418,0,0,0
600000000,400844578,600000198,1472,17411,20281,21603,1078.68,20957,0,0,0
700000000,397171569,699999003,1472,21293,21660,22086,96.94,21646,0,0,0
800000000,403385132,799999446,1472,14940,16987,19086,1257.58,16937,0,0,0 …
```

Add Dwmac 5.10a Ethernet Driver

---

benchmark/idle.c
include/sddf/benchmark/sel4bench.h

NOTE: the Following changes only affect ARM results. Related `seL4_libs` change: https://github.com/seL4/seL4_libs/pull/32
`sel4bench_get_cycle_count()` for some reason stopped PMU counters before reading from them and started afterwards. This was used in a busy loop in idle.c, causing it to miscount cycles spent in the idle thread, and most likely overall cycle counts, since any PD's/Kernel's activity that interrupted the idle thread in the middle of the function after stopping the PMU counter but before restarting it will not have its cycles counted.
* Removes `sel4bench_get_cycle_count()` and replaces its (single) use in idle.c with `SEL4BENCH_READ_CCNT()` macro.
In storage benchmarks, when computing CPU frequency, time spent in a benchmark or throughput using cycle counts on Odroid C4 …

sel4bench: Fix idle.c thread stopping PMU counters

---

benchmark/benchmark.c
benchmark/idle.c
examples/echo_server/echo.c
examples/echo_server/utilization_socket.c
include/sddf/benchmark/sel4bench.h

After the recent discovery fixed by #350, it seemed necessary to look through our included functions in `sel4_bench.h` to make sure there was nothing else incorrect. I did not find anything, but did some clean up of the included code and the files using it.
seL4 bench changes in this PR:
- Remove unused includes in c files performing benchmarking.
- Add a note about the source of our seL4 bench functions, and the ARMv8 specificity.
- Remove any definitions that we are not using.
- Add descriptions for public functions, and remove them for private functions.
This PR also includes some tidy up of `benchmark.c`:
- Changing the format of utilisation figures printed from hex to decimal - this makes sense, as they are always converted to decimal by whoever is performing the benchmark …

Clean up sel4bench

---

drivers/blk/mmc/imx/usdhc.c
examples/blk/blk.mk

* Add objcopy for timer_driver device resources and timer_client_config for blk_driver if the block driver uses a timer driver.

examples/blk: Fix blk.mk for drivers using timers

---

drivers/blk/mmc/imx/usdhc.c
include/sddf/blk/storage_info.h

Previously, if the virtualiser notified the driver whilst we were running a command (and waiting for an IRQ from the device), we acted as if received an IRQ, not a virtualiser notification. We refactor how notified() handles IRQs vs virtualiser notifications to ensure that these are kept separate in future.
Cherry picked from [`c4afbc2` (#180)](https://github.com/au-ts/sddf/pull/180/commits/c4afbc28902349bac6d9c6c5ef6a42433182c4d4) without the hotplugging changes within.
cc @dreamliner787-9 as this has not been tested after cherry-picking; this should be done before merging.

blk/mmc/imx: handle virtualiser notifications while waiting for an IRQ

---

util/cache.c

* Fix suggested by: @alwin-joshy.
* block benchmark improvements in virtualiser cpu util scaling _exponentially_ with request size, to sub exponential scaling.
Tested on branch https://github.com/au-ts/sddf/compare/szymon/benchmark_blk_rebased_sdmmc .
Idenitfied while running a block storage benchmark issuing 256 random READ requests on Odroid C4 (ARM64), SD cards used: Samsung EVO Plus 64 GB, SanDisk Extreme PRO 64GB A2, SanDisk Ultra A1 64 GB. 
The CPU utilisation for this benchmark drops significantly for all request sizes, after this change (I have been running my storage benchmarks with this mod included).
Key points on the graph: Virtualiser (solid red line) runs for a very big portion of overall CPU activity. CPU activity for LionsOS is high (dashed green line). …

util:cache.c: move dsb barrier outside of the loop.

---

ci/examples.sh
examples/serial/README.md
examples/serial/build.zig
examples/serial/meta.py
examples/serial/serial.mk

We support these two in the echo server and timer examples, so we can easily do it for the serial one as well.

examples/serial: add i.MX8MQ-EVK and i.MX8MP-EVK support

---

libco/aarch64.c
libco/amd64.c

Right now libco compiles with these warnings:
```
In file included from /Users/ivanv/ts/sddf/libco/libco.c:15:
/Users/ivanv/ts/sddf/libco/aarch64.c:48:3: warning: indirection of non-volatile null pointer will be deleted, not trap [-Wnull-dereference]
48 |   *(int *)0;  /* Panic if cothread_t entrypoint returns */
|   ^~~~~~~~~
/Users/ivanv/ts/sddf/libco/aarch64.c:48:3: note: consider using __builtin_trap() or qualifying pointer with 'volatile'
/Users/ivanv/ts/sddf/libco/aarch64.c:48:3: warning: expression result unused [-Wunused-value]
48 |   *(int *)0;  /* Panic if cothread_t entrypoint returns */
|   ^~~~~~~~~
```
This fixes that.

libco: fix warnings with __builtin_trap

---

blk/components/virt.c
include/sddf/util/cache.h
sound/components/virt.c
util/cache.c

While cache_invalidate should be all that is necessary, we cannot only do an invalidate from user-space which means we have to do system calls in order to do the cache maintenance which becomes expensive compared to cache_clean_and_invalidate, even though it has to do a clean.

blk: use cache_clean_and_invalidate instead of cache_invalidate

---

blk/components/blk_components.mk
blk/components/gpt.h
blk/components/msdos_mbr.h
blk/components/partitioning.c
blk/components/virt.c
blk/components/virt.h
build.zig
examples/blk/blk.mk
examples/blk/build.zig
tools/mkvirtdisk

The changes in block virtualiser check if the first sector is a Protective MBR in a GPT disk, and then accordingly initialise the disk. The main workflow is:
The changes in the block virtualiser check If the first sector is a Protective MBR sector, then request the following blocks containing partition table (block 1 to 4 in most cases) and the last blocks containing backup partition header and table (block -5 to -1 in most cases). After receiving all requested blocks, validate the partition header and table as well as backup partition header and table, and check if two partition headers match.
The script `mkvirtdisk` creates a MBR or GPT disk according to the last parameter.

Add support for GPT partition schema

---

blk/components/partitioning.c
blk/components/virt.c
drivers/blk/mmc/imx/blk_driver.mk
drivers/blk/mmc/imx/usdhc.c
drivers/blk/mmc/imx/usdhc.h

To be merged without squashing, see individual commit messages for more details.
Cherry picked from #180 and with an extra bugfix from @dreamliner787-9's work with virtio-blk (to be tested)

blk/mmc: miscellaneous bug fixes

---

include/sddf/benchmark/bench.h

`sddf/benchmark/bench.h` is missing a `#include <stdint.h>`.

Add missing include to bench header

---

examples/blk/meta.py
examples/echo_server/meta.py
examples/i2c/meta.py
examples/serial/meta.py
examples/timer/meta.py

Until the sDDF parts of sdfgen become part of this repo, it is common for the sdfgen version and what the metaprogram expects to become out of sync. This is especially common now due to us frequently changing both projects as sdfgen is still immature.
This assert means that at least the user knows if they are using the wrong version.
Co-authored-off-by: Courtney Darville <courtneydarville94@outlook.com>

examples: assert sdfgen version in meta.py scripts

---

examples/serial/README.md
examples/serial/build.zig
examples/serial/serial.mk

Previously we, annoyingly, had to open a separate terminal to read the virtIO console character device!
Thanks to Julia, we no longer have to do this and can instead have on stdio that contains the input/output for both the default (ns16650a) serial and our virtIO console serial driver.

examples/serial: one serial for everything for QEMU RISC-V

---

serial/components/virt_tx.c

When the tool was introduced, we accidentally left behind an additional data structure for client names which is now unused, and can be read instead from the serial config data structure. This PR removes this data structure.

Remove unused duplicate client name data structure in serial TX virtualiser

---

drivers/serial/arm/uart.c
drivers/serial/imx/uart.c
drivers/serial/meson/uart.c
drivers/serial/ns16550a/uart.c
drivers/serial/virtio/console.c

Due to a technicality with our testing set up, it was not noticed that it is possible for uart drivers to access none initialised rx data structures if the UART rx FIFO is not empty. This PR stops this from happening.

Fix uart bug causing rx queues to be serviced when rx is disabled

---

drivers/network/dwmac-5.10a/ethernet.c
drivers/network/meson/ethernet.c
drivers/network/virtio/ethernet.c

Handling transmit interrupts should be prioritised over receive interrupts to reduce RTT amongst other reasons.

Handle tx IRQs before rx IRQs in ethernet drivers

---

drivers/network/dwmac-5.10a/ethernet.c
drivers/network/dwmac-5.10a/ethernet.h

After further testing, I discovered that the `dwmac` device alters the values for buffer addresses stored in the hardware during processing, so it is not possible to rely on these values after packets have been processed. Therefore this driver requires a secondary data structure to keep track of these values.
Originally all drivers had this data structure, but it was removed recently when we realised we could read buffer addresses from the hardware ring.

Fix ethernet dwmac bug introduced by removing descriptor array

---

drivers/timer/jh7110/timer.c

While writing the zcu102 timer driver (also using 2 32-bit counters) I noticed that we might have a race condition in this driver. The following interleaving would have resulted in a wrong time reading, when processing timeouts off by up to 2^32-1 ticks in the future (potentially triggering multiple timeouts falsely):
1. IRQ for TIMEOUT counter
2. enter `get_ticks_in_ns()`
4. store `value_l` as value from the other counter (not the TIMEOUT one) register
3. store`value_h` as read from `counter_timer_elapses` global
5. **!! IRQ of OVERFLOW  for the counter !! (pending, not handled)**
6. check if IRQ pending for OVERFLOW counter
1. yes -> increment `value_h` . But `value_l` read before overflow!
7. now new `value_h` and old `value_l` give a value in the future, off by up to $2^{32}-1$ ticks! …

drivers:timer:jh7110: prevent potential race

---

.github/workflows/examples.yaml
benchmark/benchmark.c
benchmark/idle.c
ci/examples.sh
examples/echo_server/Makefile
examples/echo_server/README.md
examples/echo_server/echo.mk
examples/echo_server/meta.py
flake.nix
network/lib_sddf_lwip/lib_sddf_lwip.mk

Following changes:
- Update benchmark/benchmark.c and benchmark/idle.c to wrap arch-specific code sections in `CONFIG_ARCH_ARM` `ifdef`s. Leave skeleton for future RISC-V support.
- Restructure `echo_server` Makefile to stick to the same format as other examples: `Makefile` only creates the build directory, copies files over, minor error handling for missing params, main build file targets. `<system>.mk` does all the heavy lifting of board configs, qemu command definiton, toolchain definitions etc.
- Add qemu-virt-riscv64 support to the echo server example.

Add qemu-virt-riscv64 support for echo server. Restructure Makefile

---

docs/drivers.md

It will be useful for users to know what we actual have available, this doc should help with that.
Before merging:

docs: add list of available drivers

---

drivers/blk/virtio/block.c
drivers/gpu/virtio/gpu.c
drivers/network/virtio/ethernet.c
drivers/serial/virtio/console.c

If we handle the responses before ACKing, we run the chance of having responses appear after we (think) have processed all the responses; but then because we have ACK'd the interrupt we will have missed them and then hang.
Linux: https://elixir.bootlin.com/linux/v6.14.6/source/drivers/virtio/virtio_mmio.c#L299-L325

virtio: ack interrupts *before* handling responses

---

build.zig
examples/blk/build.zig
examples/i2c/build.zig
examples/serial/build.zig
examples/timer/build.zig

Doing `zig build` in the root of the repository no longer gives random errors. The main reason I'm making these changes is:
1. Using LazyPaths means handing relative paths (e.g SDK path) should be more reliable.
2. sDDF can be consumed as a package (I need this for sdfgen work)

build.zig: fixes and improvements

---

ci/matrix.py
drivers/serial/ns16550a/include/uart.h
drivers/serial/ns16550a/uart.c
examples/serial/serial.mk

Fixes #411.
- Fixed corruption from the DW APB shadow reset that wasn't useful
- Fixed interleaving due to not using the FIFO
- Fixed usage of a bunch of read-clear and write-clear registers

ns16550a: variety of bugfixes

---

ci/lib/backends/common.py

It would print out the following in *some* versions of Python.
Exception ignored in: <_io.TextIOWrapper encoding='UTF-8'>
AttributeError: '_TeeOut' object has no attribute 'close'
This is because we replace sys.stdout with our _TeeOut object and so then sys.stdout.close() called by python as it shuts down will fail.

ci: add close() to _TeeOut to remove ignored exception when python exits

---

examples/blk/Makefile
examples/blk/blk.mk
examples/echo_server/Makefile
examples/echo_server/echo.mk
examples/gpu/Makefile
examples/gpu/gpu.mk
examples/i2c/Makefile
examples/i2c/i2c.mk
examples/serial/Makefile
examples/serial/serial.mk
examples/timer/Makefile
examples/timer/timer.mk

This PR removes all `export override` directives from our makefiles, as discussed here #337.
It was found that `export override` is not syntactically correct in older versions of GNU make, which happen to be the default for MacOS. Also, the variables which it was being applied to were mandatory environment or command line variables, therefore the `export` had no effect. 
This PR also removes a handful of `export` directives which were not necessary (on variables which were not used in submakes).

Remove export override directives

---

util/cache.c

Most of our x86_64 patches are too in-progress to upstream but this one would make it easier for me to port libvmm since it's the only sDDF change I need to get the initial port done.

cache.c: add case for x86_64

---

.reuse/dep5
build.zig
ci/matrix.py
docs/drivers.md
drivers/timer/cdns/config.json
drivers/timer/cdns/timer.c
drivers/timer/cdns/timer_driver.mk
drivers/timer/jh7110/timer.c
examples/timer/README.md
examples/timer/build.zig
examples/timer/meta.py
examples/timer/timer.mk

Adds the cadence Triple Timer Counter (TTC) based timer driver for zcu102 board.
Also: fixes star64's jh7110 to support timeouts requiring more than UINT32_MAX counter ticks.
Caveats:
- Fixed - now does multiple timeouts (up to UINT64_MAX ticks).~max timeout allowed: ~2min 51.799s (can be extended sacrificing resolution, atm uses 25MHz clock)~
- Clock source not touched, by default uses LSBUS clock, which is downscaled from IOPLL clock (which in turn is upscaled from main source clock) - will need to be changed when clock driver introduced/any clock modifications will be done.
Draft because of the following:

drivers:timer:cdns zcu102 timer driver using cadence TTC device

---

drivers/serial/arm/uart.c
drivers/serial/imx/uart.c
drivers/serial/meson/uart.c
drivers/serial/zynqmp/uart.c
serial/components/virt_tx.c

It was discovered under certain conditions (very fast printing for a long period of time) the serial Tx subsystem can deadlock.
This was due to a failure to handle a race condition with the setting of the `producer_signalled` flag in the serial Tx virtualiser. Although the virtualiser sets the flag, it fails to double check whether the driver has done work in the meantime and possibly failed to observe the change in value of the flag.
This PR fixes this issue by adding a line of code to the virtualiser to check if the driver queue becomes free after setting the flag - thus eliminating the possible deadlock that may occur if the driver frees the queue after the initial free check but before the flag value has been updated.
While investigating this deadlock I also noticed a potential issue …

Fix serial deadlock

---

serial/components/virt_tx.c

Since ff996d3a886c31019e60af13798c3038d8688eb8 we no longer have to worry about memset not existing.

serial: cleanup in virt_tx.c

---

docs/developing.md
docs/serial/serial.md
drivers/serial/arm/serial_driver.mk
drivers/serial/imx/serial_driver.mk
drivers/serial/meson/serial_driver.mk
drivers/serial/ns16550a/serial_driver.mk
drivers/serial/virtio/serial_driver.mk
examples/serial/README.md
util/util.mk

This pull request aims to provide an example of a preferred style of documentation. Firstly, it adds a `docs` directory to the repo, which contains developer targeted documentation for using each sDDF subsystem. Secondly, it restricts the README.md documentation in the serial example to more specifically provide details of the example, leaving general subsystem informations for `docs/serial.md`.
Once a convention for such documentation is agreed upon, we should aim to update the remaining sDDF subsystems.

Create a documentation directory and updating the serial subsystem docs

---

drivers/network/dwmac-5.10a/eth_driver.mk
drivers/network/imx/eth_driver.mk
drivers/network/meson/eth_driver.mk
drivers/network/virtio/eth_driver.mk

As in title. This is needed for the LionsOS Firewall system. If there is a more optimal way to achieve this, other solutions are welcomed.

Add alternative names for ethernet driver elf files for systems that require more than one ethernet driver

---

examples/echo_server/echo.c
include/sddf/network/lib_sddf_lwip.h
network/lib_sddf_lwip/lib_sddf_lwip.c

In order to use lib sDDF LWIP in the Micropython webserver component in the LionsOS Firewall system, a number of additional features/configuration options were needed. This PR implements the following:
- Make the `pbuf` pool available to use by the client. This allows clients to allocate and free `pbuf`s to input buffers into the LWIP stack. Previously this was all handled by the `sddf_lwip_process_rx` function which processed the net queue. The firewall receives packets from the routing component which uses a firewall queue which has a slightly different interface to a net queue, thus processing must be implemented separately.
- Similarly to above, lib sDDF LWIP now supports inserting a pbuf into the LWIP network stack directly.
- Allow packets to be intercepted in between LWIP …

Add more features and configuration options to lib sDDF LWIP

---

drivers/network/dwmac-5.10a/ethernet.c
drivers/network/imx/ethernet.c
drivers/network/meson/ethernet.c
drivers/serial/arm/uart.c
drivers/serial/imx/uart.c
drivers/serial/meson/include/uart.h
drivers/serial/meson/uart.c
drivers/serial/ns16550a/include/uart.h
drivers/serial/ns16550a/uart.c
drivers/serial/zynqmp/include/uart.h
drivers/serial/zynqmp/uart.c
drivers/timer/cdns/timer.c
drivers/timer/goldfish/timer.c
drivers/timer/imx/timer.c
drivers/timer/jh7110/timer.c
drivers/timer/meson/timer.c
examples/echo_server/utilization_socket.c
examples/serial/client.c
examples/timer/client.c
include/sddf/timer/client.h

* Update serial, timer and network drivers + components to use OS agnostic sddf wrappers
* Update serial, timer, and echo_server examples in the same manner
* **DID NOT* update arp.c component and friends, due to #295
Further changes to allow Djawula to use sDDF components.

agnostic: Update network, serial and timer classes to use OS agnostic wrappers

---

drivers/network/dwmac-5.10a/ethernet.h

I ran into the UBSAN checks going off when I was trying to get virtIO network working with the HiFive P550 which uses this as the native driver.
The problem is certain defines such as `DESC_RXCTRL_RXINTDIS` have `1 << 31` which means it's shifting a 32-bit *signed* integer which by that many bits which is undefined behaviour.
We already use the BIT macro in various places in that header so just change it to use it everywhere.

drivers/network/dwmac-5.10a: use BIT macro

---

drivers/timer/jh7110/timer.c

Until we get this information from the DTS or some other automatic means, we should be careful about hard-coding it.

drivers/timer/jh7110: make timer ticks define board-specific

---

util/assert.c

We now get exceptions at '0x0000000000202a68' which corresponds to the 'previously asserting' branch.
; /sddf/util/assert.c:23
;     if (previously_asserting) {
202a64: 54000041      b.ne    0x202a6c <_assert_fail+0x1c>
; /sddf/util/assert.c:24
;         __builtin_trap();
202a68: d4200020      brk     #0x1
202a6c: a9bf7bfd      stp     x29, x30, [sp, #-0x10]!
202a70: 910003fd      mov     x29, sp
202a74: aa0303e4      mov     x4, x3
202a78: 2a0203e3      mov     w3, w2
202a7c: aa0103e2      mov     x2, x1
202a80: aa0003e1      mov     x1, x0
; /sddf/util/assert.c:27
;     sddf_dprintf("Failed assertion '%s' at %s:%u in function %s\n", assertion, file, line, function);
202a84: d503201f      nop
202a88: 10005820      adr     x0, 0x20358c
202a8c: 97fff5d5      bl      0x2001e0 <sddf_printf_> …

assert: prevent infinite recursion failures from serial assertions

---

ci/README.md
ci/lib/runner.py

This allows for you to run the example out of the standard build folder rather than needing to do a full ./ci/build.py.
$ make MICROKIT_BOARD=maaxboard
[[ builds]]
$ ../../ci/examples/blk.py --override-loaderimg build/loader.img --single --boards maaxboard
CI|INFO: Running blk on maaxboard (custom, built with custom)
CI|INFO: Acquired lock: maaxboard1 LOCKED juliab 2025-10-02 12:04:24.699846598 +1000 au_ts_ci (running locally)
[[ test runs ]]
CI|INFO: Released lock: maaxboard1 FREE
CI|INFO: Test passed
CI|INFO: Finished running blk on maaxboard (custom, built with custom)
==== Passing ====
- maaxboard: custom/custom ==== Failed ===== (none)

ci: allow passing --override-loaderimg for testing prebuild examples

---

benchmark/benchmark.c
examples/echo_server/echo.mk

I verified this by taking the pre-processor output before/after this patch for both debug and benchmark builds and making sure they were semantically the same (the only difference was the print I changed).
Closes https://github.com/au-ts/sddf/issues/402.

benchmark: simplify config checks for actually doing benchmarking

---

benchmark/benchmark.c

Fixes typo from #518 and removes preprocessor directive deadcode.
The reason for that print though is still valid IMO, as someone who compiles the code with `CONFIG_ENABLE_BENCHMARKS=1` but not on ARM, might be greeted with a silent error of benchmarking code being ignored. However, this message still gets printed, so might be enough 'guidance':
https://github.com/au-ts/sddf/blob/4618759c6f325f294d6213ff780505905ab4503d/benchmark/benchmark.c#L232

benchmark: typo fix + remove deadcode
